POST http://localhost:3000/api/auth/sign-in 
Content-Type: application/json

{
    "phoneNumber": "0546211013"
}


###

GET http://localhost:3000/api/auth/validate
x-auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdlZmY3M2EzZjU5NWI2ZGUxNTk4MWIiLCJpYXQiOjE3MDI4ODM5MzB9.k_gRfBTfAA6BcwxrRG2Y-heIOE-PP9srMgbDkQ7W33I

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "xem2",
    "email": "xem2@xem.test",
    "phoneNumber": "0546211007"
}