@host = http://localhost:3000/api/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NmMDQxYTIzMjhkMWI2MDU5MmJkOCIsImlhdCI6MTcwMzkxOTcwMH0.mijqgRksjLk-AtXcHJa8MhfgQ-2j8Zet80JSM5LJP4A
@plantId = ""
@SergeyNumber = "0546211013"
@DimaNumber = "0525856742"

@SergeyId = 657cf041a2328d1b60592bd8
@DimaId = 657d23cba2328d1b60592bda

POST {{host}}auth/sign-in 
Content-Type: application/json

{
    "phoneNumber": {{DimaNumber}}
}


###

GET http://localhost:3000/api/auth/validate
x-auth-token : {{token}}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "xem2",
    "email": "xem2@xem.test",
    "phoneNumber": "0546211007"
}
###
POST http://localhost:3000/api/plants/
x-auth-token: {{token}}
Content-Type: application/json

{
    "name": "Photos",
    "description": "Photos is a plant",
    "waterFrequency" : 2,
    "createdDate": "",
    "lastWateredDate": "",
    "nextWatering": "",
    "image": "",
    "room": "",
    "status": "",
    "userId": "657cf041a2328d1b60592bd8"
}
###
GET http://localhost:3000/api/plants/
Content-Type: application/json

{
    "name": "Cactus"
}

###
GET http://localhost:3000/api/plants
x-auth-token: {{token}}
###
PUT http://localhost:3000/api/plants/658ac555d4b082717d44d72f
Content-Type: application/json
x-auth-token: {{token}}

{
    "name": "BigCactus"
}


###
DELETE http://localhost:3000/api/plants/658ac555d4b082717d44d72f
x-auth-token : {{token}}