
POST http://localhost:3000/api/auth/sign-in 
Content-Type: application/json

{
    "phoneNumber": "0546211013"
}


###

GET http://localhost:3000/api/auth/validate
x-auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdlZmY3M2EzZjU5NWI2ZGUxNTk4MWIiLCJpYXQiOjE3MDI4ODM5MzB9.k_gRfBTfAA6BcwxrRG2Y-heIOE-PP9srMgbDkQ7W33I

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "xem2",
    "email": "xem2@xem.test",
    "phoneNumber": "0546211007"
}
###
POST http://localhost:3000/api/plants/
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTdlZmY3M2EzZjU5NWI2ZGUxNTk4MWIiLCJpYXQiOjE3MDI4ODM5MzB9.k_gRfBTfAA6BcwxrRG2Y-heIOE-PP9srMgbDkQ7W33I
Content-Type: application/json

{
    "name": "notFicus",
    "description": "notFicus is a plant",
    "waterFrequency" : 3,
    "createdDate": "",
    "lastWateredDate": "",
    "nextWatering": "",
    "image": "",
    "room": "",
    "status": "",
    "userId": "657cf041a2328d1b60592bd8"
}
###
GET http://localhost:3000/api/plants/
Content-Type: application/json

{
    "name": "Cactus"
}

###
GET http://localhost:3000/api/plants
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NmMDQxYTIzMjhkMWI2MDU5MmJkOCIsImlhdCI6MTcwMzg1MzYwNn0.27dT6t_UAqDPgZFAFRbKK-Jgm-xPFxUay9DaxubSxuc
###
PUT http://localhost:3000/api/plants/658ac555d4b082717d44d72f
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NmMDQxYTIzMjhkMWI2MDU5MmJkOCIsImlhdCI6MTcwMzYyMzQ1NH0.iD4S-VkUZ27bC6aLJzP1Hx6XEE6qNQrA5PYX6irFqF0

{
    "name": "BigCactus"
}


###
DELETE http://localhost:3000/api/plants/658afee42a2073c6b8b5304e
x-auth-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1N2NmMDQxYTIzMjhkMWI2MDU5MmJkOCIsImlhdCI6MTcwMzYyMzQ1NH0.iD4S-VkUZ27bC6aLJzP1Hx6XEE6qNQrA5PYX6irFqF0